apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-app
  template:
    metadata:
      labels:
        app: fiap-app
    spec:
      containers:
      - name: fiap-app
        image: soareshelio/fiap-app:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: app-secret
